version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka-1:
    image: wurstmeister/kafka
    container_name: kafka-1
    ports:
      - "9095:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.14
      KAFKA_ADVERTISED_PORT: 9095
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 500
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-2:
    image: wurstmeister/kafka
    container_name: kafka-2
    ports:
      - "9096:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.14
      KAFKA_ADVERTISED_PORT: 9096
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 501
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-3:
    image: wurstmeister/kafka
    container_name: kafka-3
    ports:
      - "9097:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.14
      KAFKA_ADVERTISED_PORT: 9097
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 502
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock